export const products = [
  {
    name: 'Logo Fast',
    slug: 'logo-fast',
    shortDescription: 'Create a beautiful logo in seconds with AI.',
    description: '',
    websiteUrl: 'https://shipfa.st/tools/logo-fast',
    imageUrl: '/logofast.png',
    likes: 50,
    comments: ['Logo Maker'],
    pricingModel: 'Fixed',
    tags: ['Next.js', 'AI'],
    youtubeUrl: 'https://www.youtube.com/watch?v=video123',
    isPromoted: true,
    status: 'FEATURED',
    createdBy: {
      id: 'user123',
      name: 'John Doe',
      email: 'john@example.com',
    },
    createdAt: '2024-04-07T12:00:00.000Z',
    updatedAt: '2024-04-07T12:00:00.000Z',
  },
  {
    name: 'App Brews',
    slug: 'app-brews',
    shortDescription:
      'Get High-performance Next.js Boilerplate for your micro saas.',
    description:
      'Laptop Y is a sleek and powerful device built for multitasking and productivity. It boasts a high-resolution display, fast processor, and long battery life.',
    websiteUrl: 'https://appbrews.co',
    imageUrl: '/appbrews.png',
    likes: 20,
    comments: ['Great laptop for work!', 'Impressive performance.'],
    pricingModel: 'Subscription',
    tags: ['laptop', 'technology', 'work'],
    youtubeUrl: null,
    isPromoted: false,
    status: 'NEW',
    createdBy: {
      id: 'user456',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    createdAt: '2024-04-08T09:30:00.000Z',
    updatedAt: '2024-04-08T09:30:00.000Z',
  },
  {
    name: 'Ship Fast',
    slug: 'ship-fast',
    shortDescription: 'Launch your startup in days, not weeks.',
    description: '',
    websiteUrl: 'https://shipfa.st',
    imageUrl: '/shipfast.png',
    likes: 15,
    comments: [],
    pricingModel: 'Onetime',
    tags: ['Next.js'],
    youtubeUrl: null,
    isPromoted: false,
    status: 'NEW',
    createdBy: {
      id: 'user789',
      name: 'Alice Johnson',
      email: 'alice@example.com',
    },
    createdAt: '2024-04-09T15:45:00.000Z',
    updatedAt: '2024-04-09T15:45:00.000Z',
  },
  {
    name: 'Micro Launch',
    slug: 'micro-launch',
    shortDescription: 'Discover the latest product trends on Microlaunch.',
    description:
      'Smart Watch A tracks your workouts, monitors your health, and keeps you connected on the go. Its sleek design and customizable faces make it the perfect accessory.',
    websiteUrl: 'https://microlaunch.net',
    imageUrl: '/microlaunch.png',
    likes: 35,
    comments: ['Love the design!', 'Great battery life.'],
    pricingModel: 'Subscription',
    tags: ['smartwatch', 'wearable', 'fitness'],
    youtubeUrl: 'https://www.youtube.com/watch?v=video456',
    isPromoted: true,
    status: 'TRENDING',
    createdBy: {
      id: 'user123',
      name: 'John Doe',
      email: 'john@example.com',
    },
    createdAt: '2024-04-10T11:20:00.000Z',
    updatedAt: '2024-04-10T11:20:00.000Z',
  },
  {
    name: 'Lara Fast',
    slug: 'larafast',
    shortDescription: 'Launch your startup in days with Laravel',
    description:
      'Camera B features high-resolution imaging, advanced autofocus, and manual controls for capturing stunning photos and videos.',
    websiteUrl: 'https://larafast.com',
    imageUrl: '/larafast.png',
    likes: 10,
    comments: ["Best camera I've ever used!", 'Impressive image quality.'],
    pricingModel: 'Fixed',
    tags: ['camera', 'photography', 'professional'],
    youtubeUrl: 'https://www.youtube.com/watch?v=video789',
    isPromoted: false,
    status: 'FEATURED',
    createdBy: {
      id: 'user456',
      name: 'Jane Smith',
      email: 'jane@example.com',
    },
    createdAt: '2024-04-11T14:00:00.000Z',
    updatedAt: '2024-04-11T14:00:00.000Z',
  },
];

export const plans = [
  {
    _id: 1,
    name: 'Free',
    icon: '/assets/icons/free-plan.svg',
    price: 0,
    credits: 10,
    inclusions: [
      {
        label: '10 Free Credits',
        isIncluded: true,
      },
      {
        label: 'Basic Access to Services',
        isIncluded: true,
      },
      {
        label: 'Priority Customer Support',
        isIncluded: false,
      },
      {
        label: 'Priority Updates',
        isIncluded: false,
      },
    ],
  },
  {
    _id: 2,
    name: 'Pro Package',
    icon: '/assets/icons/free-plan.svg',
    price: 49,
    credits: 120,
    inclusions: [
      {
        label: '120 Credits',
        isIncluded: true,
      },
      {
        label: 'Full Access to Services',
        isIncluded: true,
      },
      {
        label: 'Priority Customer Support',
        isIncluded: true,
      },
      {
        label: 'Priority Updates',
        isIncluded: false,
      },
    ],
  },
  {
    _id: 3,
    name: 'Premium Package',
    icon: '/assets/icons/free-plan.svg',
    price: 199,
    credits: 500,
    inclusions: [
      {
        label: '500 Credits',
        isIncluded: true,
      },
      {
        label: 'Full Access to Services',
        isIncluded: true,
      },
      {
        label: 'Priority Customer Support',
        isIncluded: true,
      },
      {
        label: 'Priority Updates',
        isIncluded: true,
      },
    ],
  },
];
